name: MirrorRepo

on:
  push:
  delete:
  
jobs:
  gitlab:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync
        run: |
          # 打印输入参数
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}

          # 添加镜像源
          if [ `git remote -v | awk '{print $1}' | grep gitlab | wc -l` = 0 ]; then
              git remote add gitlab git@gitlab.com:gaoyang/test-mirror.git
          fi
          git remote -v

          # 处理各种 event
          if [ "${{ github.event_name }}" == "push" ]; then
            git checkout ${{ github.ref_name }}
            git pull
            git push gitlab ${{ github.ref_name }}
          elif [ "${{ github.event_name }}" == "delete" ]; then
            echo "delete"
            git push -d mirror ${{ github.ref_name }}
          fi


#           git@gitlab.com:joycastle/bingo/client/bingo.git
#           ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
