name: MirrorRepo

on:
  create:
  push:
  delete:
  
jobs:
  gitlab:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: sync
        run: |
          # 添加 mirror 源
          if [ `git remote -v | awk '{print $1}' | grep gitlab | wc -l` = 0 ]; then
              git remote add gitlab git@gitlab.com:gaoyang/test-mirror.git
          fi

          git remote -v

          echo ${{ github.ref_name }}
          
          # if [ "${{ github.event_name }}" == "create" ] || [ "${{ github.event_name }}" == "push" ]; then
          #     echo "create or push"
          #     git checkout ${{ github.ref_name }}
          #     git pull
          #     git push mirror ${github.ref_name}
          # elif [ "${{ github.event_name }}" == "delete" ]; then
          #     echo "delete"
          #     git push -d mirror ${{ github.ref_name }}
          # else
          #     echo "not support"
          # fi


#           git@gitlab.com:joycastle/bingo/client/bingo.git
#           ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
