name: MirrorRepo

on:
  push:
  delete:
  
jobs:
  gitlab:
    if: ${{ github.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync
        run: |
          # 打印输入参数
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}
          echo ${{ toJSON(github.event) }}
          echo ${{ github.event.ref }}
          
